 CREATE TABLE ZAMOWIENIA (
    ID int IDENTITY (1,1) NOT NULL,
    ZAMAWIAJACY varchar(255) NOT NULL,
    PRODUKT varchar(255) NOT NULL,
    CENA INT NOT NULL,
    EMAIL varchar(255)
);

SELECT * FROM ZAMOWIENIA

INSERT INTO ZAMOWIENIA (ZAMAWIAJACY, PRODUKT, CENA, EMAIL) VALUES ('NOWAK JAN', 'SPODNIE TURYSTYCZNE', 100, 'nowak.jan@op.pl')
INSERT INTO ZAMOWIENIA (ZAMAWIAJACY, PRODUKT, CENA, EMAIL) VALUES ('KOWALSKI ADAM', 'PLECAK TREKINGOWY', 235, 'kowalski.adam@op.pl')
INSERT INTO ZAMOWIENIA (ZAMAWIAJACY, PRODUKT, CENA, EMAIL) VALUES ('NOWAK JOANNA', 'BUTY TREKINGOWE', 350, 'nowak.joanna@op.pl')
INSERT INTO ZAMOWIENIA (ZAMAWIAJACY, PRODUKT, CENA, EMAIL) VALUES ('WELMAN ARKADIUSZ', 'GUMY DO ĆWICZEŃ', 20, 'welman.ark@op.pl')
INSERT INTO ZAMOWIENIA (ZAMAWIAJACY, PRODUKT, CENA, EMAIL) VALUES ('DWORAK FERENC', 'CZAPKA Z DASZKIEM', 20, 'dworak.ferenc@op.pl')
INSERT INTO ZAMOWIENIA (ZAMAWIAJACY, PRODUKT, CENA, EMAIL) VALUES ('TRAWA AGNIESZKA', 'MATA DO JOGI', 80, 'tr.agn@op.pl')

select * from ZAMOWIENIA where CENA = 20

select * from zamowienia where zamawiajacy like('%ak%')

select * from zamowienia order by cena

select SUM(cena) from ZAMOWIENIA

UPDATE ZAMOWIENIA SET ZAMAWIAJACY = 'NOWAK-PYC JOANNA' WHERE ZAMAWIAJACY = 'NOWAK JOANNA'
SELECT * FROM ZAMOWIENIA

